CREATE TABLE [dbo].[contacts] (
    [Id]             INT            IDENTITY (1, 1) NOT NULL,
    [Rec_No]         INT            NULL,
    [ConNum]         VARCHAR (50)   NULL,
    [ConCusnum]      VARCHAR (50)   NULL,
    [ConTitled]      NVARCHAR (50)  NULL,
    [ConFname]       NVARCHAR (50)  NULL,
    [ConLname]       NVARCHAR (50)  NULL,
    [ConName]        NVARCHAR (50)  NULL,
    [ConAdd]         NVARCHAR (50)  NULL,
    [ConAdd2]        NVARCHAR (1)   NULL,
    [ConCity]        NVARCHAR (50)  NULL,
    [ConSt]          NVARCHAR (50)  NULL,
    [ConZip]         NVARCHAR (50)  NULL,
    [ConCountry]     NVARCHAR (50)  NULL,
    [ConCszsty]      VARCHAR (50)   NULL,
    [ConEmail]       NVARCHAR (50)  NULL,
    [ConPhone]       NVARCHAR (50)  NULL,
    [ConCellphone]   NVARCHAR (50)  NULL,
    [ConPhoneext]    VARCHAR (50)   NULL,
    [ConFax]         NVARCHAR (50)  NULL,
    [ConVennum]      VARCHAR (50)   NULL,
    [ConJobtitle]    NVARCHAR (50)  NULL,
    [ConPricomms]    NVARCHAR (50)  NULL,
    [ConPrimary]     VARCHAR (50)   NULL,
    [ConPrimaryAcct] BIT            NULL,
    [ConBirthdate]   VARCHAR (50)   NULL,
    [ConWeddingdate] VARCHAR (50)   NULL,
    [ConSpouse]      NVARCHAR (50)  NULL,
    [ConSpBirthdate] VARCHAR (50)   NULL,
    [ConInactive]    VARCHAR (50)   NULL,
    [ConNotes]       NVARCHAR (200) NULL,
    CONSTRAINT [PK_contacts] PRIMARY KEY CLUSTERED ([Id] ASC)
);

