CREATE TABLE [dbo].[InvoiceDetails] (
    [Id]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [InvoiceDetailId]         BIGINT          NULL,
    [SalesOrderDetailId]      BIGINT          NULL,
    [CNCId]                   BIGINT          NULL,
    [InvoiceHeaderId]         BIGINT          NULL,
    [UserId]                  BIGINT          NULL,
    [ExchangeRate]            DECIMAL (18, 6) NULL,
    [InvoiceDate]             DATETIME2 (7)   NULL,
    [ItemNumber]              VARCHAR (250)   NULL,
    [ShipDate]                DATETIME2 (7)   NULL,
    [SOUDF001]                VARCHAR (250)   NULL,
    [Notes]                   VARCHAR (MAX)   NULL,
    [QtyShip]                 DECIMAL (18, 4) NULL,
    [QtyBackOrder]            DECIMAL (18, 4) NULL,
    [UnitCost]                DECIMAL (18, 4) NULL,
    [UnitPrice]               DECIMAL (18, 4) NULL,
    [TaxRate]                 DECIMAL (18, 4) NULL,
    [ItemMasterId]            BIGINT          NULL,
    [CoreCharge]              DECIMAL (18, 4) NULL,
    [ClosedUpdate]            VARCHAR (10)    NULL,
    [AgentId]                 BIGINT          NULL,
    [TaxAmount]               DECIMAL (18, 4) NULL,
    [CalcTax]                 VARCHAR (10)    NULL,
    [DailyLeaseMethod]        VARCHAR (250)   NULL,
    [FromDate]                DATETIME2 (7)   NULL,
    [QtyReturned]             DECIMAL (18, 4) NULL,
    [QtyReturnedTotal]        DECIMAL (18, 4) NULL,
    [SalesPeriodId]           BIGINT          NULL,
    [SCCId]                   BIGINT          NULL,
    [BillCoreCharge]          VARCHAR (10)    NULL,
    [CustomerRef]             VARCHAR (250)   NULL,
    [PartMerge]               VARCHAR (10)    NULL,
    [UpdateFromStr]           VARCHAR (250)   NULL,
    [CustomerPrice]           DECIMAL (18, 4) NULL,
    [Converted]               VARCHAR (10)    NULL,
    [SerialNumber]            VARCHAR (250)   NULL,
    [PrintNonstockFlag]       VARCHAR (10)    NULL,
    [CMCId]                   BIGINT          NULL,
    [SPNOverride]             VARCHAR (250)   NULL,
    [CMCOverride]             VARCHAR (250)   NULL,
    [InvoiceDetailOriginalId] BIGINT          NULL,
    [InvoiceDetailCreditedId] BIGINT          NULL,
    [ShippingDetailId]        BIGINT          NULL,
    [QtyOrdered]              DECIMAL (18, 4) NULL,
    [DSCId]                   BIGINT          NULL,
    [PackageOverride]         VARCHAR (250)   NULL,
    [RouteCode]               VARCHAR (50)    NULL,
    [RouteDescription]        VARCHAR (250)   NULL,
    [SalesPeriodId2]          BIGINT          NULL,
    [CMCId2]                  BIGINT          NULL,
    [SPNOverride2]            VARCHAR (250)   NULL,
    [CMCOverride2]            VARCHAR (250)   NULL,
    [CoreChargeTaxRate]       DECIMAL (18, 4) NULL,
    [PDLId]                   BIGINT          NULL,
    [WorkOrderQuoteDetailId]  BIGINT          NULL,
    [SetCustomerPrice]        VARCHAR (10)    NULL,
    [MarketInvoiceDetailId]   BIGINT          NULL,
    [MarketNotes]             VARCHAR (MAX)   NULL,
    [SDF_IND_001]             VARCHAR (250)   NULL,
    [SDF_IND_002]             VARCHAR (250)   NULL,
    [SDF_IND_003]             VARCHAR (250)   NULL,
    [SDF_IND_004]             VARCHAR (250)   NULL,
    [SDF_IND_005]             VARCHAR (250)   NULL,
    [SDF_IND_006]             VARCHAR (250)   NULL,
    [SDF_IND_007]             VARCHAR (250)   NULL,
    [SDF_IND_008]             VARCHAR (250)   NULL,
    [SDF_IND_009]             VARCHAR (250)   NULL,
    [SDF_IND_010]             VARCHAR (250)   NULL,
    [ForeignCoreCharge]       DECIMAL (18, 4) NULL,
    [Exported]                VARCHAR (10)    NULL,
    [DptRevenue]              VARCHAR (250)   NULL,
    [SkipSync]                VARCHAR (10)    NULL,
    [DoRule]                  VARCHAR (250)   NULL,
    [WorkOrderBillingId]      BIGINT          NULL,
    [RPPId]                   BIGINT          NULL,
    [ConversionId]            BIGINT          NULL,
    [CIExchange]              VARCHAR (10)    NULL,
    [LeasePeriodStart]        DATETIME2 (7)   NULL,
    [LeasePeriodEnd]          DATETIME2 (7)   NULL,
    [APCreated]               VARCHAR (10)    NULL,
    [STCId]                   BIGINT          NULL,
    [ELCId]                   BIGINT          NULL,
    [RowId]                   VARCHAR (50)    NULL,
    [MasterCompanyId]         BIGINT          NULL,
    [Migrated_Id]             BIGINT          NULL,
    [SuccessMsg]              VARCHAR (500)   NULL,
    [ErrorMsg]                VARCHAR (500)   NULL,
    CONSTRAINT [PK_InvoiceDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

