CREATE TABLE [dbo].[InvoiceHeaders] (
    [Id]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [InvoiceHeaderId]        BIGINT          NULL,
    [InvoiceNumber]          VARCHAR (100)   NULL,
    [TextTemplateId]         BIGINT          NULL,
    [CustomerId]             BIGINT          NULL,
    [CurrencyId]             BIGINT          NULL,
    [ShipViaCodeId]          BIGINT          NULL,
    [TermCodeId]             BIGINT          NULL,
    [UserId]                 BIGINT          NULL,
    [NumberOfItems]          DECIMAL (18, 4) NULL,
    [TotalCost]              DECIMAL (18, 4) NULL,
    [TotalPrice]             DECIMAL (18, 4) NULL,
    [Attention]              VARCHAR (250)   NULL,
    [AirwayBill]             VARCHAR (100)   NULL,
    [BillAddress1]           VARCHAR (250)   NULL,
    [BillAddress2]           VARCHAR (250)   NULL,
    [BillAddress3]           VARCHAR (250)   NULL,
    [BillAddress4]           VARCHAR (250)   NULL,
    [BillAddress5]           VARCHAR (250)   NULL,
    [BillName]               VARCHAR (250)   NULL,
    [ClauseList]             VARCHAR (MAX)   NULL,
    [CompanyPONumber]        VARCHAR (100)   NULL,
    [CompanyDept]            VARCHAR (250)   NULL,
    [Instructions]           VARCHAR (MAX)   NULL,
    [InvoiceDate]            DATETIME2 (7)   NULL,
    [Notes]                  VARCHAR (MAX)   NULL,
    [OrderDate]              DATETIME2 (7)   NULL,
    [PicklistNotes]          VARCHAR (MAX)   NULL,
    [PrintDate]              DATETIME2 (7)   NULL,
    [QtyCartons]             INT             NULL,
    [ShipAddress1]           VARCHAR (250)   NULL,
    [ShipAddress2]           VARCHAR (250)   NULL,
    [ShipAddress3]           VARCHAR (250)   NULL,
    [ShipAddress4]           VARCHAR (250)   NULL,
    [ShipAddress5]           VARCHAR (250)   NULL,
    [ShipNumber]             VARCHAR (100)   NULL,
    [ShipName]               VARCHAR (250)   NULL,
    [ShipDate]               DATETIME2 (7)   NULL,
    [SoldBy]                 VARCHAR (250)   NULL,
    [TaxAmount]              DECIMAL (18, 4) NULL,
    [Weight]                 DECIMAL (18, 4) NULL,
    [FOB]                    VARCHAR (250)   NULL,
    [PostStatus]             INT             NULL,
    [PostDescription]        VARCHAR (100)   NULL,
    [Priority]               INT             NULL,
    [ClosedUpdate]           VARCHAR (10)    NULL,
    [DepartmentId]           BIGINT          NULL,
    [SystemCompanyId]        BIGINT          NULL,
    [FaxNumber]              VARCHAR (100)   NULL,
    [PhoneNumber]            VARCHAR (100)   NULL,
    [EmailAddress]           VARCHAR (250)   NULL,
    [TaxMethod]              VARCHAR (50)    NULL,
    [ForeignAmount]          DECIMAL (18, 4) NULL,
    [SalesPeriodId]          BIGINT          NULL,
    [AgentId]                BIGINT          NULL,
    [CustomerContactId]      BIGINT          NULL,
    [TrackingNumber]         VARCHAR (250)   NULL,
    [ToPrint]                VARCHAR (10)    NULL,
    [ExportedFlag]           VARCHAR (10)    NULL,
    [ExternalBatch]          VARCHAR (100)   NULL,
    [Converted]              VARCHAR (10)    NULL,
    [AccountId]              BIGINT          NULL,
    [ShipViaAccountId]       BIGINT          NULL,
    [PaymentAmount]          DECIMAL (18, 4) NULL,
    [ForeignPaymentAmount]   DECIMAL (18, 4) NULL,
    [ExchangeRate]           DECIMAL (18, 6) NULL,
    [PaymentId]              BIGINT          NULL,
    [BankId]                 BIGINT          NULL,
    [CheckNumber]            VARCHAR (100)   NULL,
    [CreditCardId]           BIGINT          NULL,
    [PRHId]                  BIGINT          NULL,
    [HazmatNotes]            VARCHAR (MAX)   NULL,
    [InvoiceType]            VARCHAR (10)    NULL,
    [PostDate]               DATETIME2 (7)   NULL,
    [WorkOrderQuoteHeaderId] BIGINT          NULL,
    [USRId]                  BIGINT          NULL,
    [MarketInvoiceId]        BIGINT          NULL,
    [QBTransactionId]        VARCHAR (100)   NULL,
    [QBTransaction]          VARCHAR (100)   NULL,
    [SDF_INH_001]            VARCHAR (250)   NULL,
    [SDF_INH_002]            VARCHAR (250)   NULL,
    [SDF_INH_003]            VARCHAR (250)   NULL,
    [SDF_INH_004]            VARCHAR (250)   NULL,
    [SDF_INH_005]            VARCHAR (250)   NULL,
    [SDF_INH_006]            VARCHAR (250)   NULL,
    [SDF_INH_007]            VARCHAR (250)   NULL,
    [SDF_INH_008]            VARCHAR (250)   NULL,
    [SDF_INH_009]            VARCHAR (250)   NULL,
    [SDF_INH_010]            VARCHAR (250)   NULL,
    [ELCId]                  BIGINT          NULL,
    [ProformaNumber]         VARCHAR (100)   NULL,
    [SCCId]                  BIGINT          NULL,
    [CountryOfOriginId]      BIGINT          NULL,
    [DTCId]                  BIGINT          NULL,
    [IN_UDF_001]             VARCHAR (250)   NULL,
    [PostedByUserId]         BIGINT          NULL,
    [BatchNumber]            VARCHAR (100)   NULL,
    [MsgAkInvoice]           VARCHAR (100)   NULL,
    [EDIInvoiceSent]         VARCHAR (10)    NULL,
    [WOOProgress]            VARCHAR (100)   NULL,
    [SkipSync]               VARCHAR (10)    NULL,
    [TrackChanges]           VARCHAR (10)    NULL,
    [InternalFlag]           VARCHAR (10)    NULL,
    [WorkOrderOutgoingId]    BIGINT          NULL,
    [DateCreated]            DATETIME2 (7)   NULL,
    [PostTimestamp]          DATETIME2 (7)   NULL,
    [ConversionId]           BIGINT          NULL,
    [MsgAkASN]               VARCHAR (100)   NULL,
    [EDIASNSent]             VARCHAR (10)    NULL,
    [WOODeposit]             VARCHAR (10)    NULL,
    [PaymentReceived]        VARCHAR (10)    NULL,
    [AmountReceived]         DECIMAL (18, 4) NULL,
    [CCCustomerName]         VARCHAR (250)   NULL,
    [CCStreetAddress]        VARCHAR (250)   NULL,
    [CCCityStateZip]         VARCHAR (250)   NULL,
    [ExpirationDate]         DATETIME2 (7)   NULL,
    [VisiblePortal]          VARCHAR (10)    NULL,
    [PostExchangeRate]       DECIMAL (18, 6) NULL,
    [AuthorizedByUserId]     BIGINT          NULL,
    [AuthorizeAmount]        DECIMAL (18, 4) NULL,
    [ForeignAuthorizeAmount] DECIMAL (18, 4) NULL,
    [AECId]                  BIGINT          NULL,
    [AttachmentId]           BIGINT          NULL,
    [OverrideTax]            VARCHAR (10)    NULL,
    [OverrideTaxDate]        DATETIME2 (7)   NULL,
    [AvataxEnable]           VARCHAR (10)    NULL,
    [ValidatedShipAddress]   VARCHAR (MAX)   NULL,
    [MasterCompanyId]        BIGINT          NULL,
    [Migrated_Id]            BIGINT          NULL,
    [SuccessMsg]             VARCHAR (500)   NULL,
    [ErrorMsg]               VARCHAR (500)   NULL,
    CONSTRAINT [PK_InvoiceHeaders] PRIMARY KEY CLUSTERED ([Id] ASC)
);

