CREATE TABLE [dbo].[ItemMasters] (
    [Id]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [ItemMasterId]         BIGINT          NULL,
    [CurrencyId]           BIGINT          NULL,
    [ItemGroupId]          BIGINT          NULL,
    [ItemClassificationId] BIGINT          NULL,
    [ManufacturerId]       BIGINT          NULL,
    [UnitOfMeasureId]      BIGINT          NULL,
    [PartNumber]           VARCHAR (100)   NULL,
    [PartDescription]      VARCHAR (MAX)   NULL,
    [Hazard_Material]      VARCHAR (10)    NULL,
    [DER_Flag]             VARCHAR (10)    NULL,
    [Reorder_Cond_Level]   DECIMAL (18, 2) NULL,
    [MinimumOrderQuantity] INT             NULL,
    [PartListPrice]        DECIMAL (18, 2) NULL,
    [NotesAdded]           VARCHAR (5000)  NULL,
    [IsActive]             VARCHAR (10)    NULL,
    [Date_Created]         DATETIME2 (7)   NULL,
    [IsTimeLife]           VARCHAR (10)    NULL,
    [IsSerialized]         VARCHAR (10)    NULL,
    [Shelf_Life]           VARCHAR (10)    NULL,
    [List_Price_Date]      DATETIME2 (7)   NULL,
    [ECC_Number]           VARCHAR (100)   NULL,
    [ITAR_Number]          VARCHAR (100)   NULL,
    [Shelf_Life_Days]      INT             NULL,
    [PMA_Flag]             VARCHAR (10)    NULL,
    [Procurement]          VARCHAR (100)   NULL,
    [IsHOTPart]            VARCHAR (10)    NULL,
    [LeadDays]             INT             NULL,
    [MasterCompanyId]      BIGINT          NULL,
    [Migrated_Id]          BIGINT          NULL,
    [SuccessMsg]           VARCHAR (500)   NULL,
    [ErrorMsg]             VARCHAR (500)   NULL,
    [SalesPrice]           DECIMAL (18, 2) NULL,
    [Alert]                VARCHAR (MAX)   NULL,
    [UOM]                  VARCHAR (50)    NULL,
    [VendorId]             BIGINT          NULL,
    [Condition]            VARCHAR (100)   NULL,
    [PartType]             VARCHAR (100)   NULL,
    [StockLevel]           INT             NULL,
    [ReOrderPoint]         INT             NULL,
    [QtyOH]                INT             NULL,
    [QtyReserved]          INT             NULL,
    CONSTRAINT [PK_ItemMasters] PRIMARY KEY CLUSTERED ([Id] ASC)
);

