CREATE TABLE [dbo].[PurchaseOrderHeaders] (
    [Id]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [POHeaderId]       BIGINT          NULL,
    [PONumber]         VARCHAR (100)   NULL,
    [VendorId]         BIGINT          NULL,
    [CurrencyId]       BIGINT          NULL,
    [ShipViaCodeId]    BIGINT          NULL,
    [TermsCondtionId]  BIGINT          NULL,
    [UserId]           BIGINT          NULL,
    [Attention]        VARCHAR (250)   NULL,
    [CompanyRefNumber] VARCHAR (250)   NULL,
    [EntryDate]        DATETIME2 (7)   NULL,
    [FaxNumber]        VARCHAR (100)   NULL,
    [HistoricalFlag]   VARCHAR (10)    NULL,
    [Notes]            VARCHAR (500)   NULL,
    [TotalCost]        DECIMAL (18, 2) NULL,
    [OpenFlag]         VARCHAR (100)   NULL,
    [PhoneNumber]      VARCHAR (100)   NULL,
    [RecDate]          DATETIME2 (7)   NULL,
    [Remarks]          VARCHAR (250)   NULL,
    [ResaleFlag]       VARCHAR (10)    NULL,
    [VendorAddress1]   VARCHAR (250)   NULL,
    [VendorAddress2]   VARCHAR (250)   NULL,
    [VendorAddress3]   VARCHAR (250)   NULL,
    [VendorAddress4]   VARCHAR (250)   NULL,
    [VendorAddress5]   VARCHAR (250)   NULL,
    [ShipAddress1]     VARCHAR (250)   NULL,
    [ShipAddress2]     VARCHAR (250)   NULL,
    [ShipAddress3]     VARCHAR (250)   NULL,
    [ShipAddress4]     VARCHAR (250)   NULL,
    [ShipAddress5]     VARCHAR (250)   NULL,
    [ShipDate]         DATETIME2 (7)   NULL,
    [FOB]              VARCHAR (100)   NULL,
    [EmailAddress]     VARCHAR (100)   NULL,
    [PoShipDate]       DATETIME2 (7)   NULL,
    [DeferredRec]      VARCHAR (100)   NULL,
    [DATE_CREATED]     DATETIME2 (7)   NULL,
    [Date_Modified]    DATETIME2 (7)   NULL,
    [Priority]         INT             NULL,
    [MasterCompanyId]  BIGINT          NULL,
    [Migrated_Id]      BIGINT          NULL,
    [SuccessMsg]       VARCHAR (500)   NULL,
    [ErrorMsg]         VARCHAR (500)   NULL,
    CONSTRAINT [PK_PurchaseOrderHeaders_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

