CREATE TABLE [dbo].[PurchaseOrderParts] (
    [Id]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [POPartId]             BIGINT          NULL,
    [ItemMasterId]         BIGINT          NULL,
    [AltItemMasterId]      BIGINT          NULL,
    [ConditionId]          BIGINT          NULL,
    [UnitOfMeasureId]      BIGINT          NULL,
    [POHeaderId]           BIGINT          NULL,
    [UserId]               BIGINT          NULL,
    [BuyAsType]            VARCHAR (50)    NULL,
    [EntryDate]            DATETIME2 (7)   NULL,
    [ExchangeRate]         DECIMAL (18, 2) NULL,
    [ItemNumber]           VARCHAR (100)   NULL,
    [LastDeliveryDate]     DATETIME2 (7)   NULL,
    [NextDeliveryDate]     DATETIME2 (7)   NULL,
    [Notes]                VARCHAR (MAX)   NULL,
    [QtyBackOrder]         INT             NULL,
    [QtyOrdered]           INT             NULL,
    [QtyRec]               INT             NULL,
    [UnitCost]             DECIMAL (18, 2) NULL,
    [STR_Id]               INT             NULL,
    [VendorPrice]          DECIMAL (18, 2) NULL,
    [POCategoryId]         BIGINT          NULL,
    [SODetailLink]         VARCHAR (100)   NULL,
    [ReceiverInstr]        VARCHAR (200)   NULL,
    [DSC_Id]               BIGINT          NULL,
    [Warehouse_Id]         BIGINT          NULL,
    [ListPrice]            DECIMAL (18, 2) NULL,
    [Remarks]              VARCHAR (250)   NULL,
    [EDINumber]            VARCHAR (100)   NULL,
    [ConsignmentCodeId]    BIGINT          NULL,
    [HasPieceParts]        VARCHAR (10)    NULL,
    [SHM_Id]               BIGINT          NULL,
    [StockCategoryCodeId]  BIGINT          NULL,
    [WorkOrderOperationId] BIGINT          NULL,
    [ShipDate]             DATETIME2 (7)   NULL,
    [TrackingNumber]       VARCHAR (250)   NULL,
    [MasterCompanyId]      BIGINT          NULL,
    [Migrated_Id]          BIGINT          NULL,
    [SuccessMsg]           VARCHAR (500)   NULL,
    [ErrorMsg]             VARCHAR (500)   NULL,
    [UOM]                  VARCHAR (50)    NULL,
    CONSTRAINT [PK_PurchaseOrderParts_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

