CREATE TABLE [dbo].[SalesOrderHeaders] (
    [Id]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderHeaderId] BIGINT          NOT NULL,
    [CustomerId]         BIGINT          NULL,
    [AgentId]            BIGINT          NULL,
    [SystemUserId]       BIGINT          NULL,
    [CurrencyId]         BIGINT          NULL,
    [ShipViaCodeId]      BIGINT          NULL,
    [SalesOrderNum]      NVARCHAR (50)   NULL,
    [Attention]          NVARCHAR (200)  NULL,
    [CompRefNum]         NVARCHAR (4000) NULL,
    [DueDate]            DATETIME        NULL,
    [EntryDate]          DATETIME        NULL,
    [FaxNumber]          NVARCHAR (50)   NULL,
    [HistoricalFlag]     NVARCHAR (10)   NULL,
    [RecDate]            DATETIME        NULL,
    [Notes]              NVARCHAR (MAX)  NULL,
    [NoOfItems]          INT             NULL,
    [TotalCost]          DECIMAL (18, 4) NULL,
    [TotalPrice]         DECIMAL (18, 4) NULL,
    [OpenFlag]           NVARCHAR (10)   NULL,
    [PhoneNumber]        NVARCHAR (50)   NULL,
    [ExchangeRate]       DECIMAL (18, 4) NULL,
    [EmailAddress]       NVARCHAR (200)  NULL,
    [FOB]                NVARCHAR (100)  NULL,
    [BillName]           NVARCHAR (200)  NULL,
    [ShipName]           NVARCHAR (200)  NULL,
    [BillAddress1]       NVARCHAR (200)  NULL,
    [BillAddress2]       NVARCHAR (200)  NULL,
    [BillAddress3]       NVARCHAR (200)  NULL,
    [BillAddress4]       NVARCHAR (200)  NULL,
    [BillAddress5]       NVARCHAR (200)  NULL,
    [ShipAddress1]       NVARCHAR (200)  NULL,
    [ShipAddress2]       NVARCHAR (200)  NULL,
    [ShipAddress3]       NVARCHAR (200)  NULL,
    [ShipAddress4]       NVARCHAR (200)  NULL,
    [ShipAddress5]       NVARCHAR (200)  NULL,
    [TermsCodeId]        BIGINT          NULL,
    [CountryCodeId]      BIGINT          NULL,
    [DateCreated]        DATETIME        NULL,
    [MasterCompanyId]    BIGINT          NULL,
    [Migrated_Id]        BIGINT          NULL,
    [SuccessMsg]         NVARCHAR (MAX)  NULL,
    [ErrorMsg]           NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_SalesOrderHeaders] PRIMARY KEY CLUSTERED ([Id] ASC)
);

