CREATE TABLE [dbo].[SalesOrderQuoteHeaders] (
    [Id]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderQuoteHeaderId] BIGINT          NOT NULL,
    [CustomerId]              BIGINT          NULL,
    [SystemUserId]            BIGINT          NULL,
    [CurrencyId]              BIGINT          NULL,
    [SalesQuoteNum]           VARCHAR (100)   NULL,
    [Attention]               VARCHAR (MAX)   NULL,
    [CompRefNum]              VARCHAR (100)   NULL,
    [DueDate]                 DATETIME2 (7)   NULL,
    [EntryDate]               DATETIME2 (7)   NULL,
    [HistoricalFlag]          VARCHAR (10)    NULL,
    [Notes]                   VARCHAR (MAX)   NULL,
    [NoOfItems]               INT             NULL,
    [TotalCost]               DECIMAL (18, 2) NULL,
    [TotalPrice]              DECIMAL (18, 2) NULL,
    [EmailAddress]            VARCHAR (100)   NULL,
    [BillAddress1]            VARCHAR (100)   NULL,
    [BillAddress2]            VARCHAR (100)   NULL,
    [BillAddress3]            VARCHAR (100)   NULL,
    [BillAddress4]            VARCHAR (100)   NULL,
    [BillAddress5]            VARCHAR (100)   NULL,
    [ShipAddress1]            VARCHAR (100)   NULL,
    [ShipAddress2]            VARCHAR (100)   NULL,
    [ShipAddress3]            VARCHAR (100)   NULL,
    [ShipAddress4]            VARCHAR (100)   NULL,
    [ShipAddress5]            VARCHAR (100)   NULL,
    [TermsCodeId]             BIGINT          NULL,
    [CountryCodeId]           BIGINT          NULL,
    [DateCreated]             DATETIME2 (7)   NULL,
    [MasterCompanyId]         BIGINT          NULL,
    [Migrated_Id]             BIGINT          NULL,
    [SuccessMsg]              VARCHAR (500)   NULL,
    [ErrorMsg]                VARCHAR (500)   NULL,
    CONSTRAINT [PK_SalesOrderQuoteHeaders] PRIMARY KEY CLUSTERED ([Id] ASC)
);

