CREATE TABLE [dbo].[SalesOrderHeaders] (
    [SalesOrderHeaderId] BIGINT        NOT NULL,
    [CustomerId]         BIGINT        NULL,
    [SystemUserId]       BIGINT        NULL,
    [CurrencyId]         BIGINT        NULL,
    [ShipViaCodeId]      BIGINT        NULL,
    [SalesOrderNum]      VARCHAR (100) NULL,
    [Attention]          VARCHAR (MAX) NULL,
    [CompRefNum]         VARCHAR (100) NULL,
    [DueDate]            DATETIME2 (7) NULL,
    [EntryDate]          DATETIME2 (7) NULL,
    [HistoricalFlag]     VARCHAR (10)  NULL,
    [Notes]              VARCHAR (MAX) NULL,
    [OpenFlag]           VARCHAR (10)  NULL,
    [BillAddress1]       VARCHAR (100) NULL,
    [BillAddress2]       VARCHAR (100) NULL,
    [BillAddress3]       VARCHAR (100) NULL,
    [BillAddress4]       VARCHAR (100) NULL,
    [BillAddress5]       VARCHAR (100) NULL,
    [ShipAddress1]       VARCHAR (100) NULL,
    [ShipAddress2]       VARCHAR (100) NULL,
    [ShipAddress3]       VARCHAR (100) NULL,
    [ShipAddress4]       VARCHAR (100) NULL,
    [ShipAddress5]       VARCHAR (100) NULL,
    [TermsCodeId]        BIGINT        NULL,
    [CompanySiteId]      BIGINT        NULL,
    [SOCategoryCodeId]   BIGINT        NULL,
    [CountryCodeId]      BIGINT        NULL,
    [LastModified]       DATETIME2 (7) NULL,
    [DateCreated]        DATETIME2 (7) NULL,
    [SOStatusId]         BIGINT        NULL,
    [MasterCompanyId]    BIGINT        NULL,
    [Migrated_Id]        BIGINT        NULL,
    [SuccessMsg]         VARCHAR (500) NULL,
    [ErrorMsg]           VARCHAR (500) NULL,
    CONSTRAINT [PK_SalesOrderHeaders] PRIMARY KEY CLUSTERED ([SalesOrderHeaderId] ASC)
);

