CREATE TABLE [dbo].[SalesOrderQuoteParts] (
    [Id]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderQuotePartId]   BIGINT          NOT NULL,
    [SalesOrderQuoteHeaderId] BIGINT          NULL,
    [ItemMasterId]            BIGINT          NULL,
    [AltItemMasterId]         BIGINT          NULL,
    [ConditionId]             BIGINT          NULL,
    [UnitOfMeasureId]         BIGINT          NULL,
    [SystemUserId]            BIGINT          NULL,
    [PriorityId]              BIGINT          NULL,
    [StockRoomId]             BIGINT          NULL,
    [ItemNumber]              NVARCHAR (50)   NULL,
    [EntryDate]               DATETIME        NULL,
    [ItemNotes]               NVARCHAR (MAX)  NULL,
    [QtyQuoted]               DECIMAL (18, 4) NULL,
    [QtyRequested]            DECIMAL (18, 4) NULL,
    [UnitCost]                DECIMAL (18, 4) NULL,
    [UnitPrice]               DECIMAL (18, 4) NULL,
    [ListPrice]               DECIMAL (18, 4) NULL,
    [CustomerPrice]           DECIMAL (18, 4) NULL,
    [ForeignListPrice]        DECIMAL (18, 4) NULL,
    [ExchangeRate]            DECIMAL (18, 4) NULL,
    [ExchangeType]            NVARCHAR (50)   NULL,
    [TaxAmount]               DECIMAL (18, 4) NULL,
    [CoreCharge]              DECIMAL (18, 4) NULL,
    [Discount]                DECIMAL (18, 4) NULL,
    [QuoteAsType]             NVARCHAR (10)   NULL,
    [QuoteDate]               DATETIME        NULL,
    [NoQuoteFlag]             NVARCHAR (10)   NULL,
    [Converted]               NVARCHAR (10)   NULL,
    [SoFlag]                  NVARCHAR (10)   NULL,
    [CustRef]                 NVARCHAR (200)  NULL,
    [SodLink]                 NVARCHAR (200)  NULL,
    [SerialNumber]            NVARCHAR (100)  NULL,
    [RouteCode]               NVARCHAR (50)   NULL,
    [RouteDesc]               NVARCHAR (200)  NULL,
    [DeliveryDesc]            NVARCHAR (200)  NULL,
    [SourcePn]                NVARCHAR (100)  NULL,
    [DateCreated]             DATETIME        NULL,
    [MasterCompanyId]         BIGINT          NULL,
    [Migrated_Id]             BIGINT          NULL,
    [SuccessMsg]              NVARCHAR (MAX)  NULL,
    [ErrorMsg]                NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_SalesOrderQuoteParts] PRIMARY KEY CLUSTERED ([Id] ASC)
);

