CREATE TABLE [dbo].[ShippingHeaders] (
    [Id]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [ShippingId]                 BIGINT          NULL,
    [ShippingBatchId]            BIGINT          NULL,
    [ShipViaCodeId]              BIGINT          NULL,
    [ShippingStatusId]           BIGINT          NULL,
    [CustomerId]                 BIGINT          NULL,
    [UserId]                     BIGINT          NULL,
    [SalesOrderHeaderId]         BIGINT          NULL,
    [ShipToCustomerId]           BIGINT          NULL,
    [ShipmentNumber]             VARCHAR (100)   NULL,
    [CertNumber]                 VARCHAR (100)   NULL,
    [TrackingNumber]             VARCHAR (250)   NULL,
    [OpenFlag]                   VARCHAR (10)    NULL,
    [AirwayBill]                 VARCHAR (100)   NULL,
    [FlightNumber]               VARCHAR (100)   NULL,
    [FlightDate]                 DATETIME2 (7)   NULL,
    [ShipDate]                   DATETIME2 (7)   NULL,
    [EntryDate]                  DATETIME2 (7)   NULL,
    [ETADateTime]                DATETIME2 (7)   NULL,
    [TotalWeight]                DECIMAL (18, 4) NULL,
    [NumberOfPackages]           INT             NULL,
    [HouseAirwayBill]            VARCHAR (100)   NULL,
    [FOB]                        VARCHAR (250)   NULL,
    [Notes]                      VARCHAR (MAX)   NULL,
    [Attention]                  VARCHAR (250)   NULL,
    [PhoneNumber]                VARCHAR (100)   NULL,
    [FaxNumber]                  VARCHAR (100)   NULL,
    [EmailAddress]               VARCHAR (250)   NULL,
    [BillName]                   VARCHAR (250)   NULL,
    [BillAddress1]               VARCHAR (250)   NULL,
    [BillAddress2]               VARCHAR (250)   NULL,
    [BillAddress3]               VARCHAR (250)   NULL,
    [BillAddress4]               VARCHAR (250)   NULL,
    [BillAddress5]               VARCHAR (250)   NULL,
    [ShipName]                   VARCHAR (250)   NULL,
    [ShipAddress1]               VARCHAR (250)   NULL,
    [ShipAddress2]               VARCHAR (250)   NULL,
    [ShipAddress3]               VARCHAR (250)   NULL,
    [ShipAddress4]               VARCHAR (250)   NULL,
    [ShipAddress5]               VARCHAR (250)   NULL,
    [InvoiceHeaderId]            BIGINT          NULL,
    [RepairOrderHeaderId]        BIGINT          NULL,
    [FreightCharge]              DECIMAL (18, 4) NULL,
    [PackerName]                 VARCHAR (250)   NULL,
    [SM_UDF_001]                 VARCHAR (250)   NULL,
    [SM_UDF_002]                 VARCHAR (250)   NULL,
    [SM_UDF_003]                 VARCHAR (250)   NULL,
    [SM_UDF_004]                 VARCHAR (250)   NULL,
    [UnitOfMeasureId]            BIGINT          NULL,
    [PurchaseOrderHeaderId]      BIGINT          NULL,
    [WarehouseFrom]              VARCHAR (100)   NULL,
    [WarehouseTo]                VARCHAR (100)   NULL,
    [ShipViaAccountId]           BIGINT          NULL,
    [HazmatNotes]                VARCHAR (MAX)   NULL,
    [SDF_SMH_001]                VARCHAR (250)   NULL,
    [SDF_SMH_002]                VARCHAR (250)   NULL,
    [SDF_SMH_003]                VARCHAR (250)   NULL,
    [SDF_SMH_004]                VARCHAR (250)   NULL,
    [SDF_SMH_005]                VARCHAR (250)   NULL,
    [SDF_SMH_006]                VARCHAR (250)   NULL,
    [SDF_SMH_007]                VARCHAR (250)   NULL,
    [SDF_SMH_008]                VARCHAR (250)   NULL,
    [SDF_SMH_009]                VARCHAR (250)   NULL,
    [SDF_SMH_010]                VARCHAR (250)   NULL,
    [WorkOrderOutgoingId]        BIGINT          NULL,
    [CurrencyId]                 BIGINT          NULL,
    [CompanyDropShip]            VARCHAR (250)   NULL,
    [CustomerDropShip]           VARCHAR (250)   NULL,
    [CountryOfOriginId]          BIGINT          NULL,
    [CODAmount]                  DECIMAL (18, 4) NULL,
    [CODCollectionType]          VARCHAR (100)   NULL,
    [CODAddCharges]              VARCHAR (100)   NULL,
    [InsidePickup]               VARCHAR (10)    NULL,
    [InsideDelivery]             VARCHAR (10)    NULL,
    [SaturdayPickup]             VARCHAR (10)    NULL,
    [SaturdayDelivery]           VARCHAR (10)    NULL,
    [SignatureOption]            VARCHAR (100)   NULL,
    [MasterFormId]               VARCHAR (100)   NULL,
    [NAFTA]                      VARCHAR (10)    NULL,
    [DTCId]                      BIGINT          NULL,
    [SalesOrderDetailId]         BIGINT          NULL,
    [FromAddress1]               VARCHAR (250)   NULL,
    [FromAddress2]               VARCHAR (250)   NULL,
    [FromCity]                   VARCHAR (100)   NULL,
    [FromState]                  VARCHAR (100)   NULL,
    [FromZip]                    VARCHAR (50)    NULL,
    [FromCountry]                VARCHAR (100)   NULL,
    [ToAddress1]                 VARCHAR (250)   NULL,
    [ToAddress2]                 VARCHAR (250)   NULL,
    [ToCity]                     VARCHAR (100)   NULL,
    [ToState]                    VARCHAR (100)   NULL,
    [ToZip]                      VARCHAR (50)    NULL,
    [SystemNoteId]               BIGINT          NULL,
    [MsgAkASN]                   VARCHAR (100)   NULL,
    [ASNSent]                    VARCHAR (10)    NULL,
    [SMSUpdate]                  DATETIME2 (7)   NULL,
    [TrackChanges]               VARCHAR (10)    NULL,
    [Hold]                       VARCHAR (10)    NULL,
    [DateCreated]                DATETIME2 (7)   NULL,
    [DutyPayor]                  VARCHAR (250)   NULL,
    [CustomsBroker]              VARCHAR (250)   NULL,
    [TrackingURL]                VARCHAR (500)   NULL,
    [HandlingOrderId]            BIGINT          NULL,
    [WorkOrderBillingId]         BIGINT          NULL,
    [WorkOrderBillingReturn]     VARCHAR (10)    NULL,
    [WorkOrderNoteId]            BIGINT          NULL,
    [ShipTimestamp]              DATETIME2 (7)   NULL,
    [ShipPriority]               INT             NULL,
    [WOOWOBShip]                 VARCHAR (10)    NULL,
    [DoNotChargeFreight]         VARCHAR (10)    NULL,
    [AssigneeUserId]             BIGINT          NULL,
    [FromAddress3]               VARCHAR (250)   NULL,
    [FromAddress4]               VARCHAR (250)   NULL,
    [CompanyFreightForwarderId]  BIGINT          NULL,
    [CustomerFreightForwarderId] BIGINT          NULL,
    [CompanyForeignConsigneeId]  BIGINT          NULL,
    [CustomerForeignConsigneeId] BIGINT          NULL,
    [WorkOrderChargeId]          BIGINT          NULL,
    [CEMId]                      BIGINT          NULL,
    [NonStock]                   VARCHAR (10)    NULL,
    [ExportRemarks]              VARCHAR (MAX)   NULL,
    [SYSCMRef]                   VARCHAR (250)   NULL,
    [MasterCompanyId]            BIGINT          NULL,
    [Migrated_Id]                BIGINT          NULL,
    [SuccessMsg]                 VARCHAR (500)   NULL,
    [ErrorMsg]                   VARCHAR (500)   NULL,
    CONSTRAINT [PK_ShippingHeaders] PRIMARY KEY CLUSTERED ([Id] ASC)
);

