CREATE TABLE [dbo].[ShippingDetails] (
    [Id]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [ShippingDetailId]        BIGINT          NULL,
    [ShippingHeaderId]        BIGINT          NULL,
    [ItemMasterId]            BIGINT          NULL,
    [Quantity]                DECIMAL (18, 4) NULL,
    [SalesOrderDetailId]      BIGINT          NULL,
    [QuantityReserved]        DECIMAL (18, 4) NULL,
    [QuantityShipped]         DECIMAL (18, 4) NULL,
    [QuantityToShip]          DECIMAL (18, 4) NULL,
    [CustomsValue]            DECIMAL (18, 4) NULL,
    [Notes]                   VARCHAR (MAX)   NULL,
    [RepairOrderDetailId]     BIGINT          NULL,
    [RPPId]                   BIGINT          NULL,
    [PurchaseOrderDetailId]   BIGINT          NULL,
    [PackageOverride]         VARCHAR (250)   NULL,
    [RouteCode]               VARCHAR (50)    NULL,
    [RouteDescription]        VARCHAR (250)   NULL,
    [SDF_SMD_001]             VARCHAR (250)   NULL,
    [SDF_SMD_002]             VARCHAR (250)   NULL,
    [SDF_SMD_003]             VARCHAR (250)   NULL,
    [SDF_SMD_004]             VARCHAR (250)   NULL,
    [SDF_SMD_005]             VARCHAR (250)   NULL,
    [SDF_SMD_006]             VARCHAR (250)   NULL,
    [SDF_SMD_007]             VARCHAR (250)   NULL,
    [SDF_SMD_008]             VARCHAR (250)   NULL,
    [SDF_SMD_009]             VARCHAR (250)   NULL,
    [SDF_SMD_010]             VARCHAR (250)   NULL,
    [PPPId]                   BIGINT          NULL,
    [ECC]                     VARCHAR (100)   NULL,
    [WorkOrderBillingId]      BIGINT          NULL,
    [UnitPrice]               DECIMAL (18, 4) NULL,
    [UnitCost]                DECIMAL (18, 4) NULL,
    [CustomerPrice]           DECIMAL (18, 4) NULL,
    [CustomerRef]             VARCHAR (250)   NULL,
    [SCCId]                   BIGINT          NULL,
    [STCId]                   BIGINT          NULL,
    [UserId]                  BIGINT          NULL,
    [ExchangeRate]            DECIMAL (18, 6) NULL,
    [EntryDate]               DATETIME2 (7)   NULL,
    [WorkOrderChargeDetailId] BIGINT          NULL,
    [ItemNumber]              VARCHAR (250)   NULL,
    [MasterCompanyId]         BIGINT          NULL,
    [Migrated_Id]             BIGINT          NULL,
    [SuccessMsg]              VARCHAR (500)   NULL,
    [ErrorMsg]                VARCHAR (500)   NULL,
    CONSTRAINT [PK_ShippingDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

