CREATE TABLE [dbo].[Stocklines] (
    [Id]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [StocklineId]         BIGINT          NULL,
    [CustomerId]          BIGINT          NULL,
    [ManufacturerId]      BIGINT          NULL,
    [ConditionId]         BIGINT          NULL,
    [WarehouseId]         BIGINT          NULL,
    [LocationId]          BIGINT          NULL,
    [ItemMasterId]        BIGINT          NULL,
    [PartNumber]          VARCHAR (8000)  NULL,
    [StocklineNumber]     VARCHAR (100)   NULL,
    [Ctrl_Number]         VARCHAR (100)   NULL,
    [Ctrl_ID]             VARCHAR (100)   NULL,
    [Qty_Received]        INT             NULL,
    [Qty_OH]              INT             NULL,
    [Qty_Available]       INT             NULL,
    [Qty_Reserved]        INT             NULL,
    [Qty_Adjusted]        INT             NULL,
    [SerialNumber]        VARCHAR (8000)  NULL,
    [ShelfLife]           VARCHAR (10)    NULL,
    [ExpirationDate]      DATETIME2 (7)   NULL,
    [MfgLotNum]           VARCHAR (100)   NULL,
    [MfgDate]             DATETIME2 (7)   NULL,
    [PartCertNumber]      VARCHAR (100)   NULL,
    [TagDate]             DATETIME2 (7)   NULL,
    [CalibRemarks]        VARCHAR (100)   NULL,
    [OrderRecDate]        DATETIME2 (7)   NULL,
    [OriginalCost]        DECIMAL (18, 2) NULL,
    [RepairOrderUnitCost] DECIMAL (18, 2) NULL,
    [RecDate]             DATETIME2 (7)   NULL,
    [ReceiverNumber]      VARCHAR (100)   NULL,
    [UnitPrice]           DECIMAL (18, 2) NULL,
    [CoreCost]            DECIMAL (18, 2) NULL,
    [UnitCost]            DECIMAL (18, 2) NULL,
    [HazardMaterial]      BIT             NULL,
    [Notes]               VARCHAR (MAX)   NULL,
    [TailNumber]          VARCHAR (100)   NULL,
    [IsIncident]          BIT             NULL,
    [IncidentReason]      VARCHAR (MAX)   NULL,
    [IsCustomerOwned]     BIT             NULL,
    [TagNumber]           VARCHAR (100)   NULL,
    [Owner]               VARCHAR (100)   NULL,
    [TaggedBy]            VARCHAR (100)   NULL,
    [IsManuallyAdded]     BIT             NULL,
    [MasterCompanyId]     BIGINT          NULL,
    [Migrated_Id]         BIGINT          NULL,
    [SuccessMsg]          VARCHAR (500)   NULL,
    [ErrorMsg]            VARCHAR (500)   NULL,
    [Date_Created]        DATETIME2 (7)   NULL,
    CONSTRAINT [PK_Stocklines_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

