CREATE TABLE [dbo].[Vendors] (
    [Id]                  INT             IDENTITY (1, 1) NOT NULL,
    [VendorId]            INT             NULL,
    [ShipViaCodeId]       INT             NULL,
    [CreditTermsId]       INT             NULL,
    [CustomerClassCodeId] INT             NULL,
    [Company_Name]        VARCHAR (100)   NULL,
    [Company_Code]        VARCHAR (100)   NULL,
    [Contact_Name]        VARCHAR (100)   NULL,
    [Phone_Number]        VARCHAR (25)    NULL,
    [Fax_Number]          VARCHAR (25)    NULL,
    [Customer_Flag]       VARCHAR (5)     NULL,
    [Vendor_Flag]         VARCHAR (5)     NULL,
    [Email_Address]       VARCHAR (100)   NULL,
    [Address1]            VARCHAR (500)   NULL,
    [Address2]            VARCHAR (500)   NULL,
    [Address3]            VARCHAR (500)   NULL,
    [City]                VARCHAR (50)    NULL,
    [State]               VARCHAR (50)    NULL,
    [Country]             VARCHAR (50)    NULL,
    [Zip_Code]            VARCHAR (30)    NULL,
    [Ship_Address1]       VARCHAR (500)   NULL,
    [Ship_Address2]       VARCHAR (500)   NULL,
    [Ship_Address3]       VARCHAR (500)   NULL,
    [Ship_City]           VARCHAR (50)    NULL,
    [Ship_State]          VARCHAR (50)    NULL,
    [Ship_Zip_Code]       VARCHAR (50)    NULL,
    [ShipToCountry]       VARCHAR (50)    NULL,
    [PBH_Flag]            VARCHAR (10)    NULL,
    [Web_Site]            VARCHAR (200)   NULL,
    [PMA_Restricted]      VARCHAR (10)    NULL,
    [DER_Restricted]      VARCHAR (10)    NULL,
    [CreatedDate]         DATETIME2 (7)   NULL,
    [UpdatedDate]         DATETIME2 (7)   NULL,
    [Restricted]          VARCHAR (10)    NULL,
    [Track_Changes]       VARCHAR (10)    NULL,
    [Notes]               VARCHAR (MAX)   NULL,
    [Credit_Limit]        DECIMAL (18, 2) NULL,
    [ATTENTION]           VARCHAR (250)   NULL,
    [Send_1099]           VARCHAR (250)   NULL,
    [Routing_Number]      VARCHAR (250)   NULL,
    [Account_Number]      VARCHAR (250)   NULL,
    [MasterCompanyId]     BIGINT          NULL,
    [Migrated_Id]         BIGINT          NULL,
    [SuccessMsg]          VARCHAR (500)   NULL,
    [ErrorMsg]            VARCHAR (500)   NULL,
    [IsActive]            BIT             NULL,
    [Terms]               VARCHAR (100)   NULL,
    CONSTRAINT [PK_Vendors_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

