CREATE TABLE [dbo].[WorkOrderTasks] (
    [WorkOrderTaskId]       BIGINT          NOT NULL,
    [WorkOrderId]           BIGINT          NULL,
    [OperationTaskId]       BIGINT          NULL,
    [WorkOrderTakMasterId]  BIGINT          NULL,
    [WorkOrderStageId]      BIGINT          NULL,
    [OperationMasterId]     BIGINT          NULL,
    [Notes]                 VARCHAR (MAX)   NULL,
    [StdDays]               INT             NULL,
    [DelayDays]             INT             NULL,
    [LastStatusChange]      DATETIME2 (7)   NULL,
    [TaskDays]              DECIMAL (18, 2) NULL,
    [DaysVar]               DECIMAL (18, 2) NULL,
    [LaborHours]            DECIMAL (18, 2) NULL,
    [LaborVar]              DECIMAL (18, 2) NULL,
    [FirstOpenDate]         DATETIME2 (7)   NULL,
    [LastCloseDate]         DATETIME2 (7)   NULL,
    [TaskStart]             DATETIME2 (7)   NULL,
    [WorkOrderParentTaskId] BIGINT          NULL,
    [SysUserId]             BIGINT          NULL,
    [SysUserSignOff]        DECIMAL (18, 2) NULL,
    [SignOffDate]           DATETIME2 (7)   NULL,
    [CustomerId]            BIGINT          NULL,
    [DateCreated]           DATETIME2 (7)   NULL,
    [MasterCompanyId]       BIGINT          NULL,
    [Migrated_Id]           BIGINT          NULL,
    [SuccessMsg]            VARCHAR (500)   NULL,
    [ErrorMsg]              VARCHAR (500)   NULL,
    CONSTRAINT [PK_WorkOrderTasks] PRIMARY KEY CLUSTERED ([WorkOrderTaskId] ASC)
);

