CREATE TABLE [dbo].[WorkOrderHeaders] (
    [WorkOrderId]         BIGINT          NOT NULL,
    [WorkOrderNumber]     VARCHAR (100)   NULL,
    [StocklineId]         BIGINT          NULL,
    [ItemMasterId]        BIGINT          NULL,
    [CustomerId]          BIGINT          NULL,
    [WorkOrderMaterialId] BIGINT          NULL,
    [SystemUserId]        BIGINT          NULL,
    [EntryDate]           DATETIME2 (7)   NULL,
    [OpenFlag]            VARCHAR (10)    NULL,
    [Notes]               VARCHAR (MAX)   NULL,
    [KitQty]              INT             NULL,
    [WorkOrderStatusId]   BIGINT          NULL,
    [OPM_Id]              BIGINT          NULL,
    [DueDate]             DATETIME2 (7)   NULL,
    [CompanyRefNumber]    VARCHAR (100)   NULL,
    [PriorityId]          INT             NULL,
    [TailNumber]          VARCHAR (100)   NULL,
    [EngineNumber]        VARCHAR (100)   NULL,
    [WarranteeFlag]       VARCHAR (10)    NULL,
    [PartConditionId]     BIGINT          NULL,
    [WoType]              VARCHAR (10)    NULL,
    [ShipViaCodeId]       BIGINT          NULL,
    [IsActive]            VARCHAR (10)    NULL,
    [Description]         VARCHAR (MAX)   NULL,
    [SalesOrderPartId]    BIGINT          NULL,
    [WorkOrderParentId]   BIGINT          NULL,
    [CurrencyId]          BIGINT          NULL,
    [CountryCodeId]       BIGINT          NULL,
    [BatchNumber]         VARCHAR (100)   NULL,
    [EstTotalCost]        DECIMAL (18, 2) NULL,
    [UrlLink]             VARCHAR (100)   NULL,
    [ReleaseDate]         DATETIME2 (7)   NULL,
    [IsTearDown]          VARCHAR (10)    NULL,
    [WorkOrderLotId]      BIGINT          NULL,
    [IntegrationType]     VARCHAR (100)   NULL,
    [IsAutoInvoice]       VARCHAR (10)    NULL,
    [DateCreated]         DATETIME2 (7)   NULL,
    [MasterCompanyId]     BIGINT          NULL,
    [Migrated_Id]         BIGINT          NULL,
    [SuccessMsg]          VARCHAR (500)   NULL,
    [ErrorMsg]            VARCHAR (500)   NULL,
    CONSTRAINT [PK_WorkOrderHeaders] PRIMARY KEY CLUSTERED ([WorkOrderId] ASC)
);

