CREATE TABLE [dbo].[WorkOrderQuoteDetails] (
    [WOQDetailId]             BIGINT          NOT NULL,
    [WOQDetailParentId]       BIGINT          NULL,
    [WOQHeaderId]             BIGINT          NULL,
    [WorkOrderRefId]          BIGINT          NULL,
    [WOTaskRefId]             BIGINT          NULL,
    [WOMaterialRefId]         BIGINT          NULL,
    [WOTaskLaborRefId]        BIGINT          NULL,
    [STIRefId]                BIGINT          NULL,
    [WOTaskSkillRefId]        BIGINT          NULL,
    [WOChargeRefId]           BIGINT          NULL,
    [Description]             VARCHAR (MAX)   NULL,
    [ItemType]                VARCHAR (50)    NULL,
    [Qty]                     BIGINT          NULL,
    [UnitPrice]               DECIMAL (18, 2) NULL,
    [ListPrice]               DECIMAL (18, 2) NULL,
    [BaseCost]                DECIMAL (18, 2) NULL,
    [Notes]                   VARCHAR (MAX)   NULL,
    [EntryDate]               DATETIME2 (7)   NULL,
    [SysUserId]               BIGINT          NULL,
    [DiscountCodeId]          BIGINT          NULL,
    [WOK_WorkOrderTaskId_Ref] BIGINT          NULL,
    [WOK_WorkOrderId_Ref]     BIGINT          NULL,
    [DueDate]                 DATETIME2 (7)   NULL,
    [Freight]                 DECIMAL (18, 2) NULL,
    [Discount]                DECIMAL (18, 2) NULL,
    [Markup]                  DECIMAL (18, 2) NULL,
    [TaxAmount]               DECIMAL (18, 2) NULL,
    [InvoiceHeaderId]         BIGINT          NULL,
    [VersionNumber]           VARCHAR (100)   NULL,
    [VersionDate]             DATETIME2 (7)   NULL,
    [ApprovalDate]            DATETIME2 (7)   NULL,
    [DateCreated]             DATETIME2 (7)   NULL,
    [MasterCompanyId]         BIGINT          NULL,
    [Migrated_Id]             BIGINT          NULL,
    [SuccessMsg]              VARCHAR (500)   NULL,
    [ErrorMsg]                VARCHAR (500)   NULL,
    CONSTRAINT [PK_WorkOrderQuoteDetails] PRIMARY KEY CLUSTERED ([WOQDetailId] ASC)
);

