CREATE TABLE [dbo].[WorkOrderMaterials] (
    [WorkOrderMaterialId] BIGINT          NOT NULL,
    [WorkOrderId]         BIGINT          NULL,
    [ItemMasterId]        BIGINT          NULL,
    [SystemUserId]        BIGINT          NULL,
    [PartConditionCodeId] BIGINT          NULL,
    [QtyNeeded]           INT             NULL,
    [QtyReserved]         INT             NULL,
    [QtyIssued]           INT             NULL,
    [QtyTurn]             INT             NULL,
    [CondLevel]           VARCHAR (100)   NULL,
    [Notes]               VARCHAR (MAX)   NULL,
    [WorkOrderTaskId]     BIGINT          NULL,
    [UnitPrice]           DECIMAL (18, 2) NULL,
    [Requisition]         VARCHAR (100)   NULL,
    [IsROPartLinked]      VARCHAR (10)    NULL,
    [IsPOPartLinked]      VARCHAR (10)    NULL,
    [IsCQDetailLinked]    VARCHAR (10)    NULL,
    [EstCost]             DECIMAL (18, 2) NULL,
    [NeedDate]            DATETIME2 (7)   NULL,
    [QtyScrapped]         INT             NULL,
    [QtyServiceable]      INT             NULL,
    [Figure]              VARCHAR (256)   NULL,
    [ConsignmentCodeId]   BIGINT          NULL,
    [QtySpare]            INT             NULL,
    [QtyPurchase]         INT             NULL,
    [Priority]            VARCHAR (100)   NULL,
    [ItemNumber]          VARCHAR (100)   NULL,
    [Remarks]             VARCHAR (MAX)   NULL,
    [OperationMasterId]   BIGINT          NULL,
    [EntryDate]           DATETIME2 (7)   NULL,
    [MasterCompanyId]     BIGINT          NULL,
    [Migrated_Id]         BIGINT          NULL,
    [SuccessMsg]          VARCHAR (500)   NULL,
    [ErrorMsg]            VARCHAR (500)   NULL,
    CONSTRAINT [PK_WorkOrderMaterials] PRIMARY KEY CLUSTERED ([WorkOrderMaterialId] ASC)
);

